version: '3.8'

services:
  app:
    build: .
    container_name: docx-pdf-converter-app
    ports:
      - "3002:3000"
    depends_on:
      gotenberg:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - GOTENBERG_URL=http://gotenberg:3000

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: gotenberg
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  default:
    name: app-network
