version: '3.8'

services:
  app:
    build: .
    container_name: docx-pdf-converter-app
    ports:
      - "3000:3000"
    depends_on:
      gotenberg:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  gotenberg:
    image: thecodingmachine/gotenberg:7
    container_name: gotenberg
    ports:
      - "3001:3001"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 2s